startup:
  package: com.RoamingStar.BlueArchive
  activity: com.yostar.supersdk.activity.YoStarSplashActivity  # com.yostar.supersdk.activity.YoStarSplashActivity
  command: am start -n {package}/{activity} #command: monkey -p {package} 1
scrcpy:
  bitrate: 100000000
  framerate: 10
adb:
  path: .\resources\adb\adb.exe
ocr:
  type: paddleocr_json # paddleocr_json / rapidocr_json / cnocr
  paddleocr_json:
    path: .\resources\ocr\PaddleOCR-json_v.1.3.1\PaddleOCR-json.exe
  rapidocr_json:
    path: .\resources\ocr\RapidOCR-json_v0.2.0\RapidOCR-json.exe
device:
  resolution:
    width: 1920
    height: 1080
  screencap: scrcpy   # adb
  touch:
    preferred_mode: minitouch # adb
    dev: /dev/input/event4
    screen_to_touch:
      touch_x: 1080 - y
      touch_y: x



# com.yostar.sdk.bridge.YoStarUnityPlayerActivity